### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by lwb4** [jonspalding/lisp-paredit#34] opened 2017-07-20 17:16 UTC
[Enter steps to reproduce:]

1. Open a Proto-REPL
2. Highlight a block of Clojure code (in my case, `(+ 2 2)`)
3. Press ctrl-alt-, then b to execute the block

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [lisp-paredit](https://github.com/jonspalding/lisp-paredit) package 0.5.5

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:854

TypeError: Cannot read property 'length' of undefined
    at barfSexp (/packages/lisp-paredit/node_modules/paredit.js/lib/editor.js:279:45)
    at /packages/lisp-paredit/lib/edit-commands.coffee:180:18
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:849:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1599:32)
    at edit (/packages/lisp-paredit/lib/edit-commands.coffee:170:10)
    at Array.barfForwards (/packages/lisp-paredit/lib/edit-commands.coffee:16:5)
    at /packages/lisp-paredit/lib/utils.coffee:51:70)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at KeymapManager.module.exports.KeymapManager.terminatePendingState (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:591:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:449:27)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -2:10.2.0 editor:consolidate-selections (input.hidden-input)
     -2:10.2.0 core:cancel (input.hidden-input)
     -2:09.0 fuzzy-finder:toggle-git-status-finder (input.hidden-input)
     -2:07.8.0 command-palette:toggle (input.hidden-input)
  8x -2:06.6.0 core:move-down (input.hidden-input)
     -2:05.1.0 core:move-up (input.hidden-input)
     -2:04.3.0 core:confirm (input.hidden-input)
     -2:04.3.0 proto-repl:execute-block (input.hidden-input)
     -1:04.3.0 settings-view:open (div.tool-panel.tree-view)
     -0:35.8.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:28.7.0 editor:newline (input.hidden-input)
     -0:27.4.0 core:backspace (input.hidden-input)
     -0:27 proto-repl:execute-text-entered-in-repl (input.hidden-input)
  2x -0:27 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:10.9.0 lisp-paredit:barf-forwards (input.hidden-input)
     -0:10.9.0 editor:move-to-previous-subword-boundary (input.hidden-input)
```

### Non-Core Packages

```
ink 0.7.4 
language-htaccess 0.1.1 
lisp-paredit 0.5.5 
proto-repl 1.4.21 
```

**Comment by neil-lindquist** [comment] 2020-04-28 01:54
I can't reproduce this error.  So, I'm going to close this issue, unless it is still happening for someone.

**Closed as completed by neil-lindquist** 2020-04-28 01:54 UTC
