### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getText' of undefined

### ISSUE THREAD

**Issue by piotrmasior** [jonspalding/lisp-paredit#32] opened 2017-03-26 19:46 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [lisp-paredit](https://github.com/jonspalding/lisp-paredit) package 0.5.5

### Stack Trace

Uncaught TypeError: Cannot read property 'getText' of undefined

```
At /home/pmasior/.atom/packages/lisp-paredit/lib/navigation-commands.coffee:30

TypeError: Cannot read property 'getText' of undefined
    at navigate (/packages/lisp-paredit/lib/navigation-commands.coffee:30:29)
    at Array.forwardSexp (/packages/lisp-paredit/lib/navigation-commands.coffee:7:5)
    at /packages/lisp-paredit/lib/utils.coffee:51:70)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  2x -0:31.6.0 core:move-up (input.hidden-input)
  4x -0:29.7.0 core:move-down (input.hidden-input)
     -0:28.8.0 core:move-up (input.hidden-input)
  3x -0:27.9.0 core:move-down (input.hidden-input)
     -0:27.1.0 core:move-up (input.hidden-input)
     -0:25.7.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:24.7.0 core:move-up (input.hidden-input)
     -0:23.4.0 core:move-down (input.hidden-input)
     -0:22.2.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:20.9.0 editor:select-to-first-character-of-line (input.hidden-input)
  7x -0:15.6.0 core:move-left (input.hidden-input)
     -0:13.9.0 core:backspace (input.hidden-input)
     -0:12 autocomplete-plus:cancel (input.hidden-input)
  4x -0:10.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:06.0 lisp-paredit:forward-sexp (input.hidden-input)
     -0:00.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
highlight-selected 0.13.1 
ink 0.6.5 
lisp-paredit 0.5.5 
Parinfer 1.17.0 
proto-repl 1.4.18 
proto-repl-charts 0.4.0 
tool-bar 1.1.0 
```

**Comment by neil-lindquist** [comment] 2020-04-16 21:48
Are there steps to reproduce this?

**Comment by neil-lindquist** [comment] 2020-07-01 21:33
I'm closing this issue since I don't know how to reproduce this.

**Closed as completed by neil-lindquist** 2020-07-01 21:33 UTC
Labels: question
